// Storage Alert Emailer — Resend notification for emergency purge events
// src/lib/jobs/storage-alert.ts
//
// Sends a single email to ADMIN_ALERT_EMAIL after the emergency storage purge
// runs, summarizing the purge result and current storage usage. The email is
// intentionally simple and actionable.
//
// If ADMIN_ALERT_EMAIL is not set, the function returns without sending.
// Resend failures are logged but not thrown, so a broken alert email never
// crashes the ingestion pipeline.

import "server-only";

import { sendEmailViaResend } from "@/lib/mail";

function getAdminEmails(): string[] {
  const raw = process.env.ADMIN_ALERT_EMAIL ?? "";
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

export interface StorageAlertPayload {
  severity: "warning" | "critical";
  currentMb: number;
  limitMb: number;
  percentage: number;
  reason: string;
  ingestionHalted: boolean;
}

function buildEmailHtml(payload: StorageAlertPayload): string {
  const { severity, currentMb, limitMb, percentage, reason, ingestionHalted } =
    payload;
  const statusColor = severity === "critical" ? "#dc2626" : "#ca8a04";
  const statusLabel = severity === "critical" ? "CRITICAL" : "WARNING";
  const haltedLine = ingestionHalted
    ? "<p><strong>New job ingestion is paused.</strong> The normalizer will continue clearing the backlog.</p>"
    : "";

  return `
    <div style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; color: #111827; background-color: #ffffff;">
      <div style="text-align: center; margin-bottom: 32px;">
        <h1 style="font-size: 24px; font-weight: 800; letter-spacing: -0.025em; color: #111827; margin: 0;">VectorMatch</h1>
      </div>
      <div style="border: 1px solid #e5e7eb; border-radius: 12px; padding: 32px; background-color: #fafafa; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
        <div style="display: inline-block; padding: 4px 12px; border-radius: 9999px; color: #ffffff; background-color: ${statusColor}; font-size: 12px; font-weight: 700; margin-bottom: 16px;">
          ${statusLabel}
        </div>
        <h2 style="font-size: 20px; font-weight: 700; color: #111827; margin-top: 0; margin-bottom: 16px;">Storage alert</h2>
        <p style="font-size: 16px; line-height: 24px; color: #4b5563; margin-top: 0; margin-bottom: 24px;">
          ${reason}
        </p>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px; color: #374151; margin-bottom: 24px;">
          <tr style="border-bottom: 1px solid #e5e7eb;">
            <td style="padding: 8px 0;">Database size</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600;">${currentMb.toFixed(0)} MB / ${limitMb} MB</td>
          </tr>
          <tr>
            <td style="padding: 8px 0;">Usage</td>
            <td style="padding: 8px 0; text-align: right; font-weight: 600;">${(percentage * 100).toFixed(1)}%</td>
          </tr>
        </table>
        ${haltedLine}
        <p style="font-size: 14px; line-height: 20px; color: #6b7280; margin-top: 0; margin-bottom: 0;">
          Set <code>FORCE_INGESTION=1</code> to override the ingestion guard in an emergency.
        </p>
      </div>
      <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 32px 0;" />
      <p style="font-size: 12px; line-height: 16px; color: #9ca3af; text-align: center; margin: 0;">
        This alert was generated by the VectorMatch storage monitor.
      </p>
    </div>
  `;
}

/**
 * Send a storage alert email to the configured admin address.
 *
 * Returns whether an email was actually sent. If ADMIN_ALERT_EMAIL is not
 * configured, returns false without error.
 */
export async function sendStorageAlertEmail(
  payload: StorageAlertPayload,
): Promise<boolean> {
  const recipients = getAdminEmails();
  if (recipients.length === 0) {
    return false;
  }

  const to = recipients.join(", ");
  const result = await sendEmailViaResend({
    to,
    subject: `[VectorMatch] Storage ${payload.severity.toUpperCase()}: ${payload.reason}`,
    html: buildEmailHtml(payload),
  });

  if (!result.success) {
    console.error("Failed to send storage alert email:", result.error);
    return false;
  }

  console.log(`Storage alert email sent to ${to} (${payload.severity})`);
  return true;
}
