import { sql } from "drizzle-orm";
import {
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import type z from "zod";

import { workplaceTypeEnum } from "./enums";

export const job = pgTable(
  "job",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    atsSource: text("ats_source").notNull(),
    atsSlug: text("ats_slug").notNull(),
    title: text("title").notNull(),
    // G7 (CORPUS_EXPANSION_TDD §1.1): rawJson is NULLed after normalization to
    // reclaim storage (~15KB → 0). The cleaned text lives in normalizedText
    // (~3KB). Made nullable so the normalizer can set it to null. During the
    // transition period (pre-backfill) legacy jobs still carry rawJson.
    rawJson: text("raw_json"),
    // G7: Cleaned, HTML-stripped job text. Populated by the normalizer after
    // extraction. rawJson is NULLed at the same time to reclaim storage. Gate 3
    // reads this instead of rawJson (no HTML stripping needed — already clean).
    normalizedText: text("normalized_text"),
    extractedTags: text("extracted_tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    jobEmbedding: vector("job_embedding", { dimensions: 1536 }),
    detectedAt: timestamp("detected_at").defaultNow(),

    // ── Module B additions (TDD §4.0c) — Deduplication & Stale Tracking ──────
    // The ATS's internal job ID (Greenhouse numeric id, Lever UUID string).
    // Combined with (atsSource, atsSlug) this is the deduplication anchor for
    // upserts during re-polls.
    externalJobId: text("external_job_id").notNull(),
    // When the job was last seen in a poll. Updated on every re-poll. Drives
    // stale detection (7 days → stale, 30 days → gone).
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    // active | stale | gone | rejected | normalization_failed.
    // - active | stale | gone: set by Module B (stale cleanup + re-poll).
    // - rejected: set by Module C Normalizer — garbage job (Gate 0 false
    //   positive, garbled listing, non-dev content). Tombstone.
    // - normalization_failed: set by Module C Normalizer — system failure
    //   (LLM fallback rate limit / timeout / OpenAI outage). Distinguishable
    //   from 'rejected' so a future retry sweep can re-process these without
    //   re-running garbage jobs. (MODULE_C_DECISIONS.md §1.1)
    // Module C's Gate 1+2 query must filter WHERE status = 'active'.
    // Resurrected to 'active' on re-poll.
    status: text("status").notNull().default("active"),
    // Module C — set when normalization completes (tags + embedding written).
    // Serves two purposes (MODULE_C_DECISIONS.md §1.2):
    //   1. Idempotency guard: jobIngestedHandler checks
    //      IF normalizedAt IS NOT NULL → skip (event re-delivery is safe).
    //   2. Retry sweep filter: WHERE status = 'normalization_failed'
    //      AND normalizedAt IS NULL identifies jobs that failed before
    //      completing normalization.
    // Set ONLY on terminal outcomes (successful normalization OR rejection).
    // NEVER set on 'normalization_failed' — that would turn it into a
    // permanent tombstone identical to 'rejected', defeating the two-status
    // split. Null = never processed by Module C.
    normalizedAt: timestamp("normalized_at"),

    // ── Extracted metadata (Phase 2 schema extension) ─────────────────────
    // Standardized fields extracted from rawJson during ingestion. These enable
    // SQL-level filtering (e.g. workplace type for remote-only matching) without
    // parsing rawJson at query time. Populated by extractJobMetadata() in
    // job-normalizer.ts. NULL when the ATS doesn't provide the field or it
    // can't be determined (notably Greenhouse workplace_type).
    workplaceType: workplaceTypeEnum("workplace_type"),
    employmentType: text("employment_type"),
    locationName: text("location_name"),
    department: text("department"),
    team: text("team"),
    applyUrl: text("apply_url"),
    publishedAt: timestamp("published_at"),
    companyName: text("company_name"),

    // ── AI-generated candidate-facing summary (added July 2026) ───────────────
    // One or two sentences focusing on the role, responsibilities, and key
    // technologies. Generated by gpt-4o-mini during normalization. Nullable
    // for legacy jobs until the backfill sweep runs.
    shortDescription: text("short_description"),

    // ── Gate 0.5 hard-blocker metadata (added July 2026) ──────────────────────
    // Extracted during normalization to support the Gate 0.5 pre-filter that
    // runs after normalization but before Gate 1+2 routing. Jobs that fail
    // Gate 0.5 are tombstoned (status='rejected') and never enter the matching
    // pipeline. See docs/reports/GATE_0_5_GEO_FENCING_HANDOFF.md.
    //
    // Region tag parsed from the job title (e.g., "- Latam", "- APAC", "- EMEA").
    // NULL when the title has no region suffix. Drives Pattern 1 detection.
    titleRegionTag: text("title_region_tag"),
    // Structured country list from ATS APIs (Ashby provides this in some
    // payloads). NULL for ATS sources without structured location data —
    // Gate 0.5 falls back to locationName parsing. Drives Pattern 2 detection.
    locationCountries: text("location_countries").array(),
    // Experience range parsed from the job description. NULL when no explicit
    // years requirement is found. Drives the experience band check (Check 5).
    experienceMinYears: integer("experience_min_years"),
    experienceMaxYears: integer("experience_max_years"),
    // Compensation range extracted from ATS APIs (Ashby compensation object,
    // Lever salaryRange). NULL when the ATS doesn't provide it. Drives the
    // compensation tier check (Check 4).
    compensationMin: numeric("compensation_min"),
    compensationMax: numeric("compensation_max"),
    compensationCurrency: text("compensation_currency"),
    // Tracks which Gate 0.5 pattern triggered the rejection, for observability.
    // Values: 'title_region_tag', 'location_country_list', 'default_on_site',
    // 'explicit_on_site', 'compensation_mismatch', 'experience_gap',
    // 'inverted_experience_band'. NULL when not rejected by Gate 0.5.
    rejectionPattern: text("rejection_pattern"),
  },
  (table) => ({
    extractedTagsIdx: index("jobs_extracted_tags_idx").using(
      "gin",
      table.extractedTags,
    ),
    embeddingIdx: index("job_embedding_hnsw_idx").using(
      "hnsw",
      table.jobEmbedding.op("vector_cosine_ops"),
    ),
    // Deduplication anchor — a job is uniquely identified by
    // (ats_source, ats_slug, external_job_id). Enables ON CONFLICT upserts.
    uniqueAtsJob: uniqueIndex("job_unique_ats_job").on(
      table.atsSource,
      table.atsSlug,
      table.externalJobId,
    ),
    // For the daily stale cleanup query (status + lastSeenAt).
    statusIdx: index("job_status_idx").on(table.status, table.lastSeenAt),
    // For the workplace type pre-filter in Gate 1 (remote-only matching).
    workplaceTypeIdx: index("job_workplace_type_idx").on(table.workplaceType),
    // For Gate 0.5 region-tag filtering.
    titleRegionTagIdx: index("job_title_region_tag_idx").on(
      table.titleRegionTag,
    ),
  }),
);

export const jobSchema = createInsertSchema(job);
export type JobSchema = z.infer<typeof jobSchema>;

export type Job = typeof job.$inferSelect;
export type NewJob = typeof job.$inferInsert;
